### ISSUE TITLE
body-name

### ISSUE THREAD

**Issue by RCpengnan** [mindayao/HSiPu2#3]
Could you tell me the number of the body parts? Such as 0 is neck,1 is left eye. Thank you !
![image](https://user-images.githubusercontent.com/74439931/175819753-7cbc6fa7-347a-479c-8753-f25ab2eec3bc.png)

**Comment by mindayao** [comment]
![features](https://user-images.githubusercontent.com/14901821/176080700-0862313e-f724-4d9b-b785-f9c789c08257.png)
The painter of this picture has graduated and I can't find the original picture file to translate Chinese to English of each part(SORRY!). I added the mark of left and right, and you also can understand the number and its corresponding body part.

**Comment by RCpengnan** [comment]
> ![features](https://user-images.githubusercontent.com/14901821/176080700-0862313e-f724-4d9b-b785-f9c789c08257.png) The painter of this picture has graduated and I can't find the original picture file to translate Chinese to English of each part(SORRY!). I added the mark of left and right, and you also can understand the number and its corresponding body part.

Thank you to your reply!
